<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Material Definitions -->
<material name="black">
<color rgba="0.1 0.1 0.1 1" />
</material>
<material name="blue">
<color rgba="0 0 1 1" />
</material>
<!-- Robot Properties -->
<xacro:property name="base_radius" value="0.1" />
<xacro:property name="base_height" value="0.1" /> <!-- Increased base height -->
<xacro:property name="wheel_radius" value="0.03" />
<xacro:property name="wheel_thickness" value="0.02" />
<!-- Base Link -->
<link name="base_link">
<visual>
<geometry>
<cylinder radius="${base_radius}" length="${base_height}" />
</geometry>
<material name="blue" /> <!-- Changed color to blue -->
</visual>
<collision>
<geometry>
<cylinder radius="${base_radius}" length="${base_height}" />
</geometry>
</collision>
<xacro:cylinder_inertia m="1.0" r="${base_radius}" h="${base_height}" xyz="0 0 0" rpy="0 0 0" />
</link>
<!-- Wheels -->
<xacro:macro name="wheel" params="prefix x_offset y_offset">
<link name="${prefix}_wheel_link">
<visual>
<geometry>
<cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
</geometry>
<origin xyz="0 0 0" rpy="1.5708 0 0" />
<material name="black" />
</visual>
<collision>
<geometry>
<cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
</geometry>
<origin xyz="0 0 0" rpy="1.5708 0 0" />
</collision>
<xacro:cylinder_inertia m="0.2" r="${wheel_radius}" h="${wheel_thickness}" xyz="0 0 0" rpy="0 0 0" />
</link>
<joint name="${prefix}_wheel_joint" type="continuous">
<parent link="base_link" />
<child link="${prefix}_wheel_link" />
<origin xyz="${x_offset} ${y_offset} ${-base_height / 2}" rpy="0 0 0" />
<axis xyz="0 1 0" />
</joint>
</xacro:macro>
<xacro:wheel prefix="left" x_offset="0" y_offset="${base_radius}" />
<xacro:wheel prefix="right" x_offset="0" y_offset="-${base_radius}" />
</robot>
